"""empty message

Revision ID: c4ca0c40225e
Revises: dce2326fdf62
Create Date: 2020-03-26 02:40:22.830148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4ca0c40225e'
down_revision = 'dce2326fdf62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata', sa.Column('Date', sa.String(), nullable=True))
    op.add_column('metadata', sa.Column('Description', sa.String(), nullable=True))
    op.add_column('metadata', sa.Column('Frequency', sa.String(), nullable=True))
    op.add_column('metadata', sa.Column('Tag', sa.String(), nullable=True))
    op.add_column('metadata', sa.Column('Title', sa.String(), nullable=True))
    op.add_column('metadata', sa.Column('Url', sa.String(), nullable=True))
    op.add_column('metadata', sa.Column('img_URL', sa.String(), nullable=True))
    op.drop_column('metadata', 'title')
    op.drop_column('metadata', 'word_count')
    op.drop_column('metadata', 'tags')
    op.drop_column('metadata', 'url')
    op.drop_column('metadata', 'pub_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata', sa.Column('pub_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('metadata', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('metadata', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('metadata', sa.Column('word_count', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('metadata', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('metadata', 'img_URL')
    op.drop_column('metadata', 'Url')
    op.drop_column('metadata', 'Title')
    op.drop_column('metadata', 'Tag')
    op.drop_column('metadata', 'Frequency')
    op.drop_column('metadata', 'Description')
    op.drop_column('metadata', 'Date')
    # ### end Alembic commands ###
